// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLTxIp3oi7CzJJImQXoL7CvQViJsg58x4',
    appId: '1:676818850163:web:0aec897aa8271c5c9f3506',
    messagingSenderId: '676818850163',
    projectId: 'dolarcito-bc004',
    authDomain: 'dolarcito-bc004.firebaseapp.com',
    storageBucket: 'dolarcito-bc004.appspot.com',
    measurementId: 'G-2796XPTH68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvDiO_hWwqa9ZFi7HXBf79HfGnh3FNs4',
    appId: '1:676818850163:android:faccdc33d1fbb08f9f3506',
    messagingSenderId: '676818850163',
    projectId: 'dolarcito-bc004',
    storageBucket: 'dolarcito-bc004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJWGc6CTxUfRx-gCTft9aTcWONSWrBkE',
    appId: '1:676818850163:ios:0488e920d610175e9f3506',
    messagingSenderId: '676818850163',
    projectId: 'dolarcito-bc004',
    storageBucket: 'dolarcito-bc004.appspot.com',
    iosBundleId: 'com.rodrig.dolarcito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxJWGc6CTxUfRx-gCTft9aTcWONSWrBkE',
    appId: '1:676818850163:ios:0488e920d610175e9f3506',
    messagingSenderId: '676818850163',
    projectId: 'dolarcito-bc004',
    storageBucket: 'dolarcito-bc004.appspot.com',
    iosBundleId: 'com.rodrig.dolarcito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLTxIp3oi7CzJJImQXoL7CvQViJsg58x4',
    appId: '1:676818850163:web:9feb3d2e5f5ac7fe9f3506',
    messagingSenderId: '676818850163',
    projectId: 'dolarcito-bc004',
    authDomain: 'dolarcito-bc004.firebaseapp.com',
    storageBucket: 'dolarcito-bc004.appspot.com',
    measurementId: 'G-7RRV2843H3',
  );
}
